#!/usr/bin/env sh

ZDOTDIR="${HOME}/zdotdir-test"
DOTY="$ZDOTDIR/.clone-doty"
DOTY_REPOSITORY_REMOTE="file://${HOME}/.doty" # "git@github.com:kw-yud/doty.git"
DOTY_REPOSITORY_BRANCH="feat/installer"

RUN_ZSH=no
GIT_CONFIG_GLOBAL="${ZDOTDIR}/.gitconfig"
DOTY_GIT_INSTALL_INTEGRATION="no"

rm -Rf "${ZDOTDIR}"

source "./scripts/doty"
