#!/usr/bin/env sh

__06_shellcheck_git_alias() {
    info "Checking git aliases $(fmt_code "$1")..."

    # shellcheck disable=SC3045,SC3003
    git config --file="$1" --null --get-regexp '^alias\.' '^!' |
    while read -r -d $'\n' key
    do
        read -r -d $'\0' value
        # shellcheck disable=SC3057
        info "    Checking $(fmt_code "${key:6}")..."  
        # shellcheck disable=SC3011,SC3057
        shellcheck --exclude SC2094,SC2119,SC2120 --shell=sh --color=always - <<< "${value:1}"
        # shellcheck disable=SC3057
        success "    Successfully checked $(fmt_code "${key:6}")."
    done

    success "Successfully checked all aliases for $(fmt_code "$1")."
}

__06_register_git_config() {
    info "Prepare git config: ${2}"
    if command_exists "shellcheck"; then
        __06_shellcheck_git_alias "$2"
    else
        warning "WARNING: Add include $(fmt_code "$1") file without shellcheck: $2"
    fi

    if git config --global --get-all "$1" | grep -q "$2"; then
        warning "Git config $(fmt_code "$2") is already loaded"
    else
       git config --global --add "$1" "$2"
    fi
}

setup_git() {
    #  Set git global options and install commons tools
    header "Configure global git options"

    info "Load git config"

    if [ "${DRY_RUN}" == "yes" ]; then
        printf '\n' >&2
        return 0
    fi

    # Ensure to use $XDG_CONFIG_HOME/git/config rather than ~/.gitconfig
    mkdir -vp "${XDG_CONFIG_HOME}/git"
    if [ -f "${zdot}/.gitconfig" ]; then
        mv "${zdot}/.gitconfig" "${XDG_CONFIG_HOME}/git/config"
    fi
    
    __06_register_git_config include.path "${DOTY}/libraries/gitalias/gitalias.txt"

    __06_register_git_config include.path "${DOTY}/config/git/.gitconfig"
    __06_register_git_config core.excludesfile "${DOTY}/config/git/gitignore"
    __06_register_git_config core.attributesfile "${DOTY}/config/git/gitattributes"

    local git_config_local_path="${DOTFILES_LOCAL_DIRECTORY}/.config/git/config.local"
    if [ ! -f "${git_config_local_path}" ]; then
        mkdir -p "$(dirname "${git_config_local_path})"
        cat <<EOF >"${git_config_local_path}"
[user]
  name = ${REAL_NAME}
  email = ${REAL_EMAIL}

EOF
    fi
    __06_register_git_config include.path "${git_config_local_path}"

    success "Git configured!"
    printf '\n' >&2
}

if [ "$SKIP_GIT_SETUP" != yes ]; then
    info "Installing git component..."
    setup_git
else
    warning "Skipping git component installation"
fi
