#!/usr/bin/env sh

setup_zellij() {
    # Setup Zellij configuration directory
    header "Setting up Zellij configuration"

    zellij setup --generate-auto-start ${SHELL} >>"$zdot/.${SHELL}rc"

    success "Zellij configuration successfully set up!"
    printf '\n' >&2
}

if [ "$SKIP_ZELLIJ_CONFIG" != yes ]; then
    info "Setup zellij configuration..."
    setup_zellij
else
    warning "Skipping zellij configuration setup"
fi