#!/usr/bin/env bash

setup_zellij() {
    # Setup Zellij configuration directory
    header "Setting up Zellij configuration"

    local current_shell
    current_shell="$(basename "${SHELL}")"
    # shellcheck disable=SC2154
    zellij setup --generate-auto-start "${current_shell}" >>"$zdot/.${current_shell}rc"

    success "Zellij configuration successfully set up!"
    printf '\n' >&2
}

if [ "$SKIP_ZELLIJ_CONFIG" != yes ]; then
    info "Setup zellij configuration..."
    setup_zellij
else
    warning "Skipping zellij configuration setup"
fi