#!/usr/bin/env sh

export KREW_ROOT="${KREW_ROOT:-"$XDG_CONFIG_HOME/kube/kube-krew"}"
export PATH="${KREW_ROOT}/bin:$PATH"

__k8s_install_kube_krew() {
    if [ "$SKIP_KUBE_SETUP" = yes ]; then
        warning "Skipping Kubernetes tools installation..."
        return
    fi

    if command_exists "kubectl-krew"; then
        success "Kube Krew already installed"
        return 0
    fi

    info "Installing Kube Krew..."

    __doty_os="$(uname -s | tr '[:upper:]' '[:lower:]')"
    __doty_arch=""
    case "$(uname -m)" in
        "x86_64") __doty_arch="amd64";;
        *) __doty_arch="$(uname -m)";;
    esac

    krew_filename="krew-${__doty_os}_${__doty_arch}"
    krew_dir="$(mktemp -d)"
    krew_file="${krew_dir}/${krew_filename}.tar.gz"
    
    if ! rcurl "https://github.com/kubernetes-sigs/krew/releases/latest/download/${krew_filename}.tar.gz" -o "${krew_file}"; then
        printf '\n' >&2
        return 1
    fi

    tar zxvf "${krew_file}" -C "${krew_dir}"
    chmod +x "${krew_dir}/krew-${__doty_os}_${__doty_arch}"
    "${krew_dir}/krew-${__doty_os}_${__doty_arch}" install krew
    rm -Rf "${krew_dir}"

    success "Successfully installing Kube Krew!"
    printf '\n' >&2
}

__k8s_install_krew_plugin() {
    if kubectl krew list | grep -E "^${1}$"; then
        info "kubectl $(fmt_code "${1}") krew plugin is already installed"
    else
        kubectl krew install "${1}"
    fi
}

# Issue:
# - https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
setup_k8s() {
    if [ "$SKIP_KUBE_SETUP" = yes ]; then
        warning "Skipping Kubernetes tools installation..."
        return
    fi

    header "Installing kubectl components"

    if __k8s_install_kube_krew; then
        __k8s_install_krew_plugin "ctx"
        __k8s_install_krew_plugin "images"
        __k8s_install_krew_plugin "neat"
        __k8s_install_krew_plugin "ns"
        __k8s_install_krew_plugin "tail"
        __k8s_install_krew_plugin "tree"
        __k8s_install_krew_plugin "view-secret"
    fi

    info "Installing fubectl..."
    mkdir -p "$XDG_CONFIG_HOME/kube"
    rcurl https://rawgit.com/kubermatic/fubectl/master/fubectl.source -o "$XDG_CONFIG_HOME/kube/fubectl.source"

    printf '\n' >&2
}

if [ "$SKIP_KUBE_SETUP" != yes ]; then
    setup_k8s
else
    warning "Skipping kube component installation"
fi

