#!/usr/bin/env sh

__05_shellcheck_git_alias() {
    info "Checking git aliases $(fmt_code "$1")..."

    git config --file="$1" --null --get-regexp '^alias\.' '^!' |
    while read -r -d $'\n' key
    do
        read -r -d $'\0' value
        info "    Checking $(fmt_code "${key:6}")..."  
        shellcheck --exclude SC2094,SC2119,SC2120 --shell=sh --color=always - <<< "${value:1}"
        success "    Successfully checked $(fmt_code "${key:6}")."
    done

    success "Successfully checked all aliases for $(fmt_code "$1")."
}

__05_register_git_config() {
    if command_exists "shellcheck"; then
        __05_shellcheck_git_alias "$2"
    else
        warning "WARNING: Add include $(fmt_code "$1") file without shellcheck: $2"
    fi

    if git config --global --get-all "$1" | grep -q "$2"; then
        warning "Git config $(fmt_code "$2") is already loaded"
    else
       git config --global --add "$1" "$2"
    fi
}

setup_git() {
    #  Set git global options and install commons tools
    header "Configure global git options"

    info "Load git config"
    
    __05_register_git_config include.path "${DOTY}/libraries/gitalias/gitalias.txt"

    __05_register_git_config include.path "${DOTY}/config/git/.gitconfig"
    __05_register_git_config core.excludesfile "${DOTY}/config/git/gitignore"
    __05_register_git_config core.attributesfile "${DOTY}/config/git/gitattributes"

    if [ "$DOTY_GIT_INSTALL_INTEGRATION" = yes ]; then
        info "Install git integration tools..."
        # Git integration
        integration_dir=$(mktemp -d)
        git clone https://github.com/johnkeeping/git-integration ${integration_dir}
        cd ${integration_dir}
        echo "${HOME}/.local" > config.mak
        make install
        make install-doc
        make install-completion

        # Exit installation directory
        cd -
    fi

    success "Git configured!"
    printf '\n' >&2
}

setup_git
