#!/usr/bin/env bash
#
# This script is based on https://github.com/ohmyzsh/ohmyzsh to install Doty.
#
# This script should be run via curl:
#   /bin/bash -c $(curl -fsSL https://raw.githubusercontent.com/yudhasetiawan/doty/main/scripts/doty)
# or via wget:
#   /bin/bash -c $(wget -qO- https://raw.githubusercontent.com/yudhasetiawan/doty/main/scripts/doty)
# or via fetch:
#   /bin/bash -c $(fetch -o - https://raw.githubusercontent.com/yudhasetiawan/doty/main/scripts/doty)
#
# As an alternative, you can first download the install script and run it afterwards:
#   wget https://raw.githubusercontent.com/yudhasetiawan/doty/main/scripts/doty
#   /bin/bash doty
#
# Run: doty --help for help and examples.
#
# You can tweak the install behavior by setting variables when running the script.
# For example, to change the path to the Doty repository:
#   DOTY=~/.local/share/doty /bin/bash doty
#
# Respects the following environment variables:
#   ZDOTDIR - path to Zsh dotfiles directory (default: unset). See [1][2]
#             [1] https://zsh.sourceforge.io/Doc/Release/Parameters.html#index-ZDOTDIR
#             [2] https://zsh.sourceforge.io/Doc/Release/Files.html#index-ZDOTDIR_002c-use-of
#   DOTY    - path to the Doty repository folder (default: $HOME/.doty)
#   REMOTE  - full remote URL of the git repo to install (default: GitHub via HTTPS https://github.com/yudhasetiawan/doty.git)
#   BRANCH  - branch to check out immediately after install (default: main)
#
# Other options:
#   DRY_RUN                   - 'yes' means the installer will dry-run the installation process without affecting the live system (default: no)
#   CHANGE_SHELL              - 'no' means the installer will not change the default shell (default: yes)
#   RUN_ZSH                   - 'no' means the installer will not run zsh after the install (default: yes)
#   KEEP_ZSHRC                - 'yes' means the installer will not replace an existing .zshrc (default: no)
#   KEEP_TMUXCONF             - 'yes' means the installer will not replace an existing .tmux.conf (default: no)
#   KEEP_NVIMCONF             - 'yes' means the installer will not replace an existing nvim/init.lua (default: no)
#   KEEP_SYMLINK              - 'yes' means the installer will not replace all symlinked files under `config/symlink` (default: no)
#   SKIP_BREW_INSTALL         - 'yes' means the installer will not install Homebrew (default: no)
#   SKIP_BREW_UPDATE          - 'yes' means the installer will not update brew (default: no)
#   SKIP_BREW_UPGRADE         - 'yes' means the installer will not upgrade brew (default: no)
#   SKIP_BREW_BUNDLE          - 'yes' means the installer will not install the brew bundle (default: no)
#   SKIP_COLORSCHEME_INSTALL  - 'yes' means the installer will not install color schemes (default: no)
#   SKIP_OSX_SETTINGS         - 'yes' means the installer will not re-configure default OS X system settings (default: yes)
#   SKIP_ZELLIJ_CONFIG        - 'yes' means the installer will not install zellij configuration (default: no)
#   SKIP_TMUX_CONFIG          - 'yes' means the installer will not install tmux configuration (default: no)
#   SKIP_TMUX_INSTALL         - 'yes' means the installer will not install tmux package (default: no)
#   SKIP_LAZYGIT_CONFIG       - 'yes' means the installer will not install lazygit configuration (default: no)
#
# You can also pass some arguments to the install script to set some these options:
#   --no-change-shell:        has the same behavior as setting CHANGE_SHELL to 'no'
#   --unattended:             sets both CHANGE_SHELL and RUN_ZSH to 'no'
#   --keep-zshrc:             sets KEEP_ZSHRC to 'yes'
#   --keep-tmux:              sets KEEP_TMUXCONF to 'yes'
#   --keep-nvim:              sets KEEP_NVIMCONF to 'yes'
#   --keep-symlink:           sets KEEP_SYMLINK to 'yes'
#   --allow-brew-install:     sets SKIP_BREW_INSTALL to 'no'
#   --skip-brew-install:      sets SKIP_BREW_INSTALL to 'yes'
#   --allow-brew-update:      sets SKIP_BREW_UPDATE to 'no'
#   --skip-brew-update:       sets SKIP_BREW_UPDATE to 'yes'
#   --allow-brew-upgrade:     sets SKIP_BREW_UPGRADE to 'no'
#   --skip-brew-upgrade:      sets SKIP_BREW_UPGRADE to 'yes'
#   --allow-brew-bundle:      sets SKIP_BREW_BUNDLE to 'no'
#   --skip-brew-bundle:       sets SKIP_BREW_BUNDLE to 'yes'
#   --allow-colorscheme-install: sets SKIP_COLORSCHEME_INSTALL to 'no'
#   --skip-colorscheme-install:  sets SKIP_COLORSCHEME_INSTALL to 'yes'
#   --allow-osx-settings:     sets SKIP_OSX_SETTINGS to 'no'
#   --skip-osx-settings:      sets SKIP_OSX_SETTINGS to 'yes'
#   --allow-zellij-config:    sets SKIP_ZELLIJ_CONFIG to 'no'
#   --skip-zellij-config:     sets SKIP_ZELLIJ_CONFIG to 'yes'
#   --allow-tmux-config:      sets SKIP_TMUX_CONFIG to 'no'
#   --skip-tmux-config:       sets SKIP_TMUX_CONFIG to 'yes'
#   --allow-tmux-install:     sets SKIP_TMUX_INSTALL to 'no'
#   --skip-tmux-install:      sets SKIP_TMUX_INSTALL to 'yes'
#   --allow-lazygit-config:   sets SKIP_LAZYGIT_CONFIG to 'no'
#   --skip-lazygit-config:    sets SKIP_LAZYGIT_CONFIG to 'yes'
# For example:
#   sh install --unattended
# or:
#   sh -c "$(curl -fsSL https://raw.githubusercontent.com/yudhasetiawan/doty/main/scripts/doty)" "" --unattended

set -e

# Make sure important variables exist if not already defined.
#
# $USER is defined by login(1) which is not always executed (e.g. containers)
# POSIX: https://pubs.opengroup.org/onlinepubs/009695299/utilities/id.html
USER=${USER:-$(id -u -n)}

# $HOME is defined at the time of login, but it could be unset. If it is unset,
# a tilde by itself (~) will not be expanded to the current user's home directory.
# POSIX: https://pubs.opengroup.org/onlinepubs/009696899/basedefs/xbd_chap08.html#tag_08_03
HOME="${HOME:-$(getent passwd "$USER" 2>/dev/null | cut -d: -f6)}"
# macOS does not have getent, but this works even if $HOME is unset.
HOME="${HOME:-$(eval echo ~"$USER")}"

# Track if $DOTY was provided.
custom_doty=${DOTY:+yes}

# Use $zdot to keep track of where the directory is for zsh dotfiles.
# To check if $ZDOTDIR was provided, explicitly check for $ZDOTDIR.
zdot=""
backup_dir=""

# Default value for $DOTY:
# a) if $ZDOTDIR is supplied and not $HOME: $ZDOTDIR/.doty
# b) otherwise, $HOME/.local/state/doty
DOTY=""

# Default settings.
DOTY_REPOSITORY_REMOTE=${DOTY_REPOSITORY_REMOTE:-https://github.com/yudhasetiawan/doty.git}
DOTY_REPOSITORY_BRANCH=${DOTY_REPOSITORY_BRANCH:-main}

# Other options.
DRY_RUN=${DRY_RUN:-no}
CHANGE_SHELL=${CHANGE_SHELL:-yes}
RUN_ZSH=${RUN_ZSH:-yes}
KEEP_ZSHRC=${KEEP_ZSHRC:-no}
KEEP_TMUXCONF=${KEEP_TMUXCONF:-no}
KEEP_NVIMCONF=${KEEP_NVIMCONF:-no}
KEEP_SYMLINK=${KEEP_SYMLINK:-no}
SKIP_DOTY_CLONE=${SKIP_DOTY_CLONE:-no}
SKIP_BREW_INSTALL=${SKIP_BREW_INSTALL:-no}
SKIP_BREW_UPDATE=${SKIP_BREW_UPDATE:-no}
SKIP_BREW_UPGRADE=${SKIP_BREW_UPGRADE:-no}
SKIP_BREW_BUNDLE=${SKIP_BREW_BUNDLE:-no}
SKIP_COLORSCHEME_INSTALL=${SKIP_COLORSCHEME_INSTALL:-no}
SKIP_OSX_SETTINGS=${SKIP_OSX_SETTINGS:-yes}
SKIP_ZELLIJ_CONFIG=${SKIP_ZELLIJ_CONFIG:-no}
SKIP_TMUX_CONFIG=${SKIP_TMUX_CONFIG:-no}
SKIP_TMUX_INSTALL=${SKIP_TMUX_INSTALL:-no}
SKIP_LAZYGIT_CONFIG=${SKIP_LAZZYGIT_CONFIG:-no}

# Enhanced package manager options
SKIP_PKG_UPDATE=${SKIP_PKG_UPDATE:-no}
SKIP_PKG_UPGRADE=${SKIP_PKG_UPGRADE:-no}
SKIP_PKG_BUNDLE=${SKIP_PKG_BUNDLE:-no}
SKIP_PKG_CLEAN=${SKIP_PKG_CLEAN:-no}
DOTY_PKG_MANAGER=${DOTY_PKG_MANAGER:-auto}

# Granular installation controls
SKIP_ZSHRC_SETUP=${SKIP_ZSHRC_SETUP:-no}
SKIP_TMUX_SETUP=${SKIP_TMUX_SETUP:-no}
SKIP_NVIM_SETUP=${SKIP_NVIM_SETUP:-no}
SKIP_GIT_SETUP=${SKIP_GIT_SETUP:-no}
SKIP_SYMLINK_SETUP=${SKIP_SYMLINK_SETUP:-no}
SKIP_FONTS_SETUP=${SKIP_FONTS_SETUP:-no}
SKIP_KUBE_SETUP=${SKIP_KUBE_SETUP:-no}
SKIP_DEVTOOLS_SETUP=${SKIP_DEVTOOLS_SETUP:-no}
SKIP_SERVICES_SETUP=${SKIP_SERVICES_SETUP:-no}
SKIP_TERMINAL_CONFIG=${SKIP_TERMINAL_CONFIG:-no}

# Environment managers
INSTALL_NVM=${INSTALL_NVM:-no}
INSTALL_PYENV=${INSTALL_PYENV:-no}
INSTALL_RBENV=${INSTALL_RBENV:-no}
INSTALL_ASDF=${INSTALL_ASDF:-no}

# Linux-specific options
SKIP_DESKTOP_SETUP=${SKIP_DESKTOP_SETUP:-no}
SKIP_SOUND_SETUP=${SKIP_SOUND_SETUP:-no}
SKIP_GRAPHICS_SETUP=${SKIP_GRAPHICS_SETUP:-no}
SKIP_GUI_TOOLS=${SKIP_GUI_TOOLS:-no}
SKIP_DESKTOP_PACKAGES=${SKIP_DESKTOP_PACKAGES:-no}

# Configuration profile
DOTY_PROFILE=${DOTY_PROFILE:-default}

# Component installation list
INSTALL_COMPONENTS=${INSTALL_COMPONENTS:-"git,zsh,tmux,nvim,packages,fonts,devtools,kube,colorscheme"}

# shellcheck disable=SC2034
{
CPU_ARCH=
OS_TYPE=
OS_KERNEL=
OS_DISTRO=
OS_DISTRO_ORIGINAL=
OS_DISTRO_LIKE=
OS_VERSION=
OS_IN_WSL="no"
OS_IN_CONTAINER="no"

DOTY_GUI_ELIGIBLE="no"
DOTY_GUI_ENABLED="no"
}

_FMT_RED=$(printf '\033[31m')
_FMT_GREEN=$(printf '\033[32m')
_FMT_YELLOW=$(printf '\033[33m')
_FMT_BLUE=$(printf '\033[34m')
_FMT_BOLD=$(printf '\033[1m')
_FMT_PURPLE=$(printf '\033[38;2;245;0;172m')
_FMT_RESET=$(printf '\033[0m')

__print_error() {
    printf '%s%s%s\n' "${_FMT_BOLD}${_FMT_RED}" "$*" "${_FMT_RESET}" >&2
}

__print_warning() {
    printf '%s%s%s\n' "${_FMT_BOLD}${_FMT_YELLOW}" "$*" "${_FMT_RESET}" >&2
}

__print_info() {
    printf '%s%s%s\n' "${_FMT_BOLD}${_FMT_BLUE}" "$*" "${_FMT_RESET}" >&2
}

__print_ok() {
    printf '%s%s%s\n' "${_FMT_BOLD}${_FMT_GREEN}" "$*" "${_FMT_RESET}" >&2
}

__print_underline() {
    printf '\033[4m%s\033[24m' "$*"
}

# shellcheck disable=SC2016 # backtick in single-quote
__print_code() {
    printf '\033[2m%s\033[22m' "$*"
}

# Header logging
__print_header() {
    text="$*"
    total_chars=${#text}

    if [ "$total_chars" -gt 80 ]; then
        total_chars=80
    fi

    printf "\033[1m$(tput setaf 7)%s$(tput sgr0)\n" "$text" >&2
    for ((i = 1; i <= total_chars; i++)); do
        printf "%s-%s" "$(tput setaf 237)" "$(tput sgr0)" >&2
    done
    printf '\n'  >&2
}

# shellcheck disable=SC2183  # printf string has more %s than arguments ($FMT_RAINBOW expands to multiple arguments)
__print_welcome() {
    printf '%s         __%s\n' "${_FMT_PURPLE}" "${_FMT_RESET}" >&2
    printf '%s    ____/ /%s\n' "${_FMT_PURPLE}" "${_FMT_RESET}" >&2
    printf '%s   / __  /%s\n' "${_FMT_PURPLE}" "${_FMT_RESET}" >&2
    printf '%s  / /_/ /%s\n' "${_FMT_PURPLE}" "${_FMT_RESET}" >&2
    printf '%s  \\____/%s    %s.... %s%s\n' "${_FMT_PURPLE}" "${_FMT_BOLD}" "${_FMT_YELLOW}" "$*" "${_FMT_RESET}" >&2
    printf '\n' >&2
    printf '%s\n%s %s\n' \
        "Before you scream ${_FMT_BOLD}${_FMT_PURPLE}Doty!${_FMT_RESET}"\
        "Look over the ${_FMT_BOLD}$(printf '\033[4m').zshrc${_FMT_RESET} file" \
        "to select plugins, themes, and options." >&2
    printf '\n%s--------------------------------------------------------------------------------%s\n\n' "${_FMT_BOLD}" "${_FMT_RESET}" >&2
}

__warn_root() {
    # This could be empty in a containerized environment.
    local user="${USER:-$(whoami)}"
    local sudo_user="${SUDO_USER:-}"

    # Indicates whether the script is running on container
    if [ -f "/.dockerenv" ] || [ -f "/run/.containerenv" ]; then
        __print_ok "Script is being run in a container"
        return
    fi

    # Root will have an effective uid of 0.
    if [ "${EUID}" != "0" ]; then
        __print_ok "Script is being run as '${user}'"
        return
    fi

    cat <<EOF
Root user detected!

$(id)

USER=${user}
SUDO_USER=${sudo_user}
EOF

    local msg="as root"
    [ -n "${sudo_user}" ] && msg="with sudo as '${sudo_user}'"

    while true; do
        printf "\nThis script is meant to run as a non-root user,\nare you sure you want to run this %s? (y/n) " "${msg}"
        read -r yn

        case "${yn}" in
            [Yy]*)
                break
                ;;
            [Nn]*)
                exit
                ;;
            *) __print_error "ERROR:   '${yn}' is not a valid answer, please input 'y' or 'n'" "" ;;
        esac
    done
}

__validate_requirements() {
    __warn_root

    if ! command -v "zsh" >/dev/null 2>&1; then
        __print_error "ERROR:   Zsh is not installed. Please install zsh first."
        exit 1
    fi

    if ! command -v "git" >/dev/null 2>&1; then
        __print_error "ERROR:   git is not installed. Please install git first."
        exit 1
    fi

    if ! command -v "vim" >/dev/null 2>&1; then
        __print_error "ERROR:   vim is not installed. Please install vim first."
        exit 1
    fi

    # Before relying on Homebrew, check that packages can be compiled
    if ! command -v "gcc" >/dev/null 2>&1 && [[ "${OSTYPE}" == darwin* ]]; then
        __print_error "ERROR:   The XCode Command Line Tools must be installed first."
        printf '\n' >&2
        printf '         Download them from: %s' "${_FMT_BOLD}$(printf '\033[4m')https://developer.apple.com/downloads${_FMT_RESET}" >&2
        exit 2
    fi

    if [ -e "$backup_dir" ]; then
        __print_error "ERROR:   Backup directory $(__print_code "$backup_dir") already exists."
        __print_error "         Can't back up files re-run the installer again in a couple of seconds."
        exit 1
    fi

    if [ -d "$DOTY" ] && [ "$SKIP_DOTY_CLONE" = no ]; then
        __print_warning "WARNING: The $(__print_code "\$DOTY") folder already exists ($DOTY)."

        if [ "$custom_doty" = yes ]; then
            cat <<EOF
You run the installer with the $(__print_code "\$DOTY") setting or the $(__print_code "\$DOTY")  variable
is exported. You have 3 options:

1. Unset the DOTY variable when calling the installer:
   $(__print_code "DOTY= sh install")
2. Install Doty to a directory that doesn't exist yet:
   $(__print_code "DOTY=path/to/new/doty/folder sh install")
3. (Caution) If the folder doesn't contain important information,
   you can just remove it with $(__print_code "rm -r $DOTY")

EOF
        else
            __print_error "ERROR:   You'll need to remove it if you want to reinstall."
        fi

        exit 1
    fi
}

# If missing, download and extract the source of doty repository
__install_doty() {
    # Prevent the cloned repository from having insecure permissions. Failing to do
    # so causes compinit() calls to fail with "command not found: compdef" errors
    # for users with insecure umasks (e.g., "002", allowing group writability). Note
    # that this will be ignored under Cygwin by default, as Windows ACLs take
    # precedence over umasks except for filesystems mounted with option "noacl".
    umask g-w,o-w

    __print_header "Cloning Doty"

    ostype=$(uname)
    if [ -z "${ostype%CYGWIN*}" ] && git --version | grep -Eq 'msysgit|windows'; then
        __print_error "ERROR:   Windows/MSYS Git is not supported on Cygwin."
        __print_error "         Make sure the Cygwin git package is installed and is first on the \$PATH"
        exit 1
    fi

    if [ ! -d "${DOTY}" ]; then
        __print_ok "Initialize Doty on $DOTY"
        git init --quiet "$DOTY"
    else
        __print_ok "Doty is already exists on $DOTY"
    fi

    cd "$DOTY"
    # Manual clone with git config options to support git < v1.7.2
    __print_ok "Update git configuration..."
    git config core.eol lf &&
        git config core.autocrlf false &&
        git config fsck.zeroPaddedFilemode ignore &&
        git config fetch.fsck.zeroPaddedFilemode ignore &&
        git config receive.fsck.zeroPaddedFilemode ignore &&
        git remote add origin "$DOTY_REPOSITORY_REMOTE" &&
        git config doty.remote origin &&
        git config doty.branch "$DOTY_REPOSITORY_BRANCH"

    (git fetch --depth=1 origin \
        && git checkout -b "$DOTY_REPOSITORY_BRANCH" "origin/$DOTY_REPOSITORY_BRANCH") || {
        [ ! -d "$DOTY" ] || {
            cd -
            rm -rf "$DOTY" 2>/dev/null
        }
        __print_error "ERROR:   git clone \"$DOTY_REPOSITORY_REMOTE\" repository failed"
        exit 1
    }

    if [ "${DRY_RUN}" != "yes" ]; then
        git submodule update --init --recursive
        # shellcheck disable=SC2016
        git submodule foreach 'git fetch origin; \
            git checkout $(git rev-parse --abbrev-ref HEAD); \
            git reset --hard origin/$(git rev-parse --abbrev-ref HEAD); \
            git submodule update --recursive --progress; \
            git clean -dfx'
    fi

    # shellcheck disable=SC2034
    DOTY_REPOSITORY_COMMIT="$(git -C "${DOTY}" log -1 --format="%as :: %h :: %s" 2>/dev/null || echo "-")"

    # Exit installation directory
    cd -

    __print_ok "Doty is cloned on $DOTY"
    printf '\n' >&2
}

__install() {
    # Create ZDOTDIR folder structure if it doesn't exist
    if [ -n "$ZDOTDIR" ]; then
        mkdir -p "$ZDOTDIR"
    fi

    __print_welcome "is now installing"

    if [ -d "$DOTY" ] && [ "$SKIP_DOTY_CLONE" = yes ]; then
        __print_warning "WARNING: reuse existing doty directory ($DOTY)"
    else
        __install_doty
    fi

    # Create backup_dir folder structure if it doesn't exist
    if [ -n "$backup_dir" ]; then
        mkdir -p "$backup_dir"
    fi

    # shellcheck disable=SC1091
    source "${DOTY}/scripts/utils"

    if ! command_exists "shellcheck"; then
        __print_warning "WARNING: shellcheck is not installed"

        if ! prompt "Are you want to continue without running shellcheck?"; then
            __print_error "Cancelled..."
            exit 1
        fi
    else
        __print_info "INFO:    Using shellcheck: $(shellcheck --version)"
    fi

    # Make sure a `.local/doty/install-config` always exists.
    if [ ! -f "${DOTY}/.local/doty/install-config" ]; then
        mkdir -p "${DOTY}/.local/doty"
        cp -n "${DOTY}/scripts/install-config.dist" "${DOTY}/.local/doty/install-config"
    fi

    detect_os
    __configure_configuration
    # shellcheck disable=SC1091
    source "${DOTY}/.local/doty/install-config"

    for __installer in $(find -H "${DOTY}/scripts/installer" -maxdepth 1 -type f -not -name '*.dist' | sort -u); do
        __print_info "INFO:    Running installer: ${__installer}"
        # TODO: Ensure to run shellcheck properly
        if command_exists "shellcheck"; then
            shellcheck --shell=bash --color=always - <<< "$(cat "${__installer}")"
        else
            __print_warning "WARNING: Sourcing ${__installer} without shellcheck"
        fi

        if ! prompt "         do you want to continue?"; then
            __print_error "Skip installer ${__installer}..."
            continue
        fi

        # shellcheck disable=SC1090
        if ! source "${__installer}"; then
            __print_warning "WARNING: The installer ${__installer} return with an error"
            if ! prompt "do you want to continue the installer?"; then
                __print_error "Abort installer..."
                exit 1
            fi
        fi

        printf '\n' >&2
    done

    printf '\n' >&2
    printf "$(tput setaf 64)✓$(tput sgr0) %s%s%s\n" "${_FMT_BOLD}${_FMT_PURPLE}" "Doty is now installed!" "${_FMT_RESET}" >&2
    printf '\n' >&2
    __print_ok "You can safely close this terminal."
    __print_ok "The next time you open your terminal everything will be ready to go!"
    printf '\n' >&2

    if [ "${RUN_ZSH}" = "no" ]; then
        __print_header "                      "
        __print_warning "Run zsh to try it out."
        printf '\n' >&2
        exit
    fi

    printf '\n' >&2
    exec zsh -l
}

__ask_for_name() {
    __print_header "Asking for your name"

    local name
    if [ -n "${REAL_NAME}" ]; then
        __print_warning "WARNING: \"${REAL_NAME}\" was retrieved from your install config"
        return 0
    fi

    if name="$(git config user.name)"; then
        __print_ok "\"${name}\" was retrieved from your git config"
    else
        while true; do
            read -rp "What is your full name (ie. Alice)? " name
            if [[ ${name} =~ [^[:space:]]+ ]]; then
                break
            else
                __print_error "ERROR:   Please enter at least your name"
            fi
        done
    fi

    REAL_NAME="${name}"
}

__ask_for_email() {
    __print_header "Asking for your e-mail"

    local name
    if [ -n "${REAL_EMAIL}" ]; then
        __print_warning "WARNING: \"${REAL_EMAIL}\" was retrieved from your install config"
        return 0
    fi

    if email="$(git config user.email)"; then
        __print_ok "\"${email}\" was retrieved from your git config"
    else
        while true; do
            read -rp "What is your email address (ie. bob@example.com)? " email
            if [[ ${email} =~ .+@.+ ]]; then
                break
            else
                __print_error "ERROR:   Please enter a valid email address"
            fi
        done
    fi

    REAL_EMAIL="${email}"
}

__configure_configuration() {
    __print_header "What would you like to do for installation configuration?"

    local not_eligible=" ${_FMT_RED}[NOT ELIGIBLE]${_FMT_RESET}"
    [ "${DOTY_GUI_ELIGIBLE}" = "yes" ] && not_eligible=

    cat <<EOF
${_FMT_GREEN}Your system is ready to install Doty.

${_FMT_BOLD}${_FMT_BLUE}1) Reset to default configuration (command line + GUI)${not_eligible}${_FMT_RESET}
2) Command line only
3) Command line and GUI${not_eligible}
${_FMT_YELLOW}4) Review which packages get installed and overwrite default config (optional)${_FMT_RESET}

EOF

    while true; do
        read -rp "Which option number would you like to configure? [1] " option
        printf '\n' >&2
        
        if [ -z "${option}" ]; then
            cp -fn "${DOTY}/scripts/install-config.dist" "${DOTY}/.local/doty/install-config"

            break
        fi

        case "${option}" in
        1)
            cp -fn "${DOTY}/scripts/install-config.dist" "${DOTY}/.local/doty/install-config"

            __configure_configuration
            ;;
        2)
            perl -pi -e 's|export DOTY_GUI_ENABLED=.*|export DOTY_GUI_ENABLED="no"|g;' "${DOTY}/.local/doty/install-config"
            break
            ;;
        3)
            if [ "${DOTY_GUI_ELIGIBLE}" != "yes" ]; then
                cat <<EOF

${_FMT_RED}Sorry your OS isn't eligible, this option requires all of these to be true:${_FMT_RESET}

- Running an Arch based Linux distro [Yours: ${OS_DISTRO}]
- Not running within WSL (Windows Subsystem for Linux) [Yours: ${OS_IN_WSL}]
- Not running in a container [Yours: ${OS_IN_CONTAINER}]
EOF

                continue
            fi

            perl -pi -e 's|export DOTY_GUI_ENABLED=.*|export DOTY_GUI_ENABLED="yes"|g;' "${DOTY}/.local/doty/install-config"
            break
            ;;
        4)
            vim "${DOTY}/.local/doty/install-config"

            __configure_configuration
            ;;
        *)
            __print_error "ERROR:   \"${option}\" isn't a valid choice, pick 1, 2 or 3"
            ;;
        esac
    done

    __ask_for_name
    __ask_for_email
}

main() {
    # Run as unattended if stdin is not a tty
    if [ ! -t 0 ]; then
        RUN_ZSH=no
        CHANGE_SHELL=no
        PACKAGES_AUTO_CONFIRM=yes
    fi

    # Parse arguments
    # shellcheck disable=SC2034
    {
        while [ $# -gt 0 ]; do
            case $1 in
            --unattended)
                RUN_ZSH=no
                CHANGE_SHELL=no
                shift
                ;;
            --no-change-shell)
                CHANGE_SHELL=no
                shift
                ;;
            --keep-zshrc)
                KEEP_ZSHRC=yes
                shift
                ;;
            --keep-tmux)
                KEEP_TMUXCONF=yes
                shift
                ;;
            --keep-nvim)
                KEEP_NVIMCONF=yes
                shift
                ;;
            --keep-symlink)
                KEEP_SYMLINK=yes
                shift
                ;;
            --allow-brew-update)
                SKIP_BREW_UPDATE=no
                shift
                ;;
            --skip-brew-update)
                SKIP_BREW_UPDATE=yes
                shift
                ;;
            --allow-brew-upgrade)
                SKIP_BREW_UPGRADE=no
                shift
                ;;
            --skip-brew-upgrade)
                SKIP_BREW_UPGRADE=yes
                shift
                ;;
            --allow-brew-bundle)
                SKIP_BREW_BUNDLE=no
                shift
                ;;
            --skip-brew-bundle)
                SKIP_BREW_BUNDLE=yes
                shift
                ;;
            --allow-brew-install)
                SKIP_BREW_INSTALL=no
                shift
                ;;
            --skip-brew-install)
                SKIP_BREW_INSTALL=yes
                shift
                ;;
            --allow-colorscheme-install)
                SKIP_COLORSCHEME_INSTALL=no
                shift
                ;;
            --skip-colorscheme-install)
                SKIP_COLORSCHEME_INSTALL=yes
                shift
                ;;
            --allow-osx-settings)
                SKIP_OSX_SETTINGS=no
                shift
                ;;
            --skip-osx-settings)
                SKIP_OSX_SETTINGS=yes
                shift
                ;;
            --allow-zellij-config)
                SKIP_ZELLIJ_CONFIG=no
                shift
                ;;
            --skip-zellij-config)
                SKIP_ZELLIJ_CONFIG=yes
                shift
                ;;
            --allow-tmux-config)
                SKIP_TMUX_CONFIG=no
                shift
                ;;
            --skip-tmux-config)
                SKIP_TMUX_CONFIG=yes
                shift
                ;;
            --allow-tmux-install)
                SKIP_TMUX_INSTALL=no
                shift
                ;;
            --skip-tmux-install)
                SKIP_TMUX_INSTALL=yes
                shift
                ;;
            --allow-lazygit-config)
                SKIP_LAZYGIT_CONFIG=no
                shift
                ;;
            --skip-lazygit-config)
                SKIP_LAZYGIT_CONFIG=yes
                shift
                ;;
            esac
        done

        if [ "${DRY_RUN}" = "yes" ]; then
            ZDOTDIR="$(mktemp -d)"
            RUN_ZSH=no
            PACKAGES_AUTO_CONFIRM=no
        fi

        # Use $zdot to keep track of where the directory is for zsh dotfiles.
        # To check if $ZDOTDIR was provided, explicitly check for $ZDOTDIR.
        zdot="${ZDOTDIR:-$HOME}"
        backup_dir="${DOTY_BACKUP_DIR:-"${zdot}/.config/doty-backups"}/$(date +%Y%m%d%H%M%S)"

        # Default value for $DOTY:
        # a) if $ZDOTDIR is supplied and not $HOME: $ZDOTDIR/.doty
        # b) otherwise, $HOME/.local/share/doty
        [ "$ZDOTDIR" = "$HOME" ] || DOTY="${DOTY:-${ZDOTDIR:+$ZDOTDIR/.doty}}"
        DOTY="${DOTY:-$HOME/.local/share/doty}"
    }

    __validate_requirements
    __install
}

# Always run these when calling the script, even sourcing it.
main "$@"