#!/bin/sh

outfile="$(mktemp -d)/meslo.zip"

curl -s "https://api.github.com/repos/ryanoasis/nerd-fonts/releases/latest" \
  | jq -r '.assets[] | .browser_download_url | select(contains("Meslo.zip"))' \
  | wget -O "${outfile}" -i - 

unzip "${outfile}" -d ~/Library/Fonts

