#!/usr/bin/env sh

set -e

# Use colors, but only if connected to a terminal
# and that terminal supports them.

# The [ -t 1 ] check only works when the function is not called from
# a subshell (like in `$(...)` or `(...)`, so this hack redefines the
# function at the top level to always return false when stdout is not
# a tty.
if [ -t 1 ]; then
    is_tty() {
        true
    }
else
    is_tty() {
        false
    }
fi

# Adapted from code and information by Anton Kochkov (@XVilka)
# Source: https://gist.github.com/XVilka/8346728
supports_truecolor() {
    case "$COLORTERM" in
    truecolor | 24bit) return 0 ;;
    esac

    case "$TERM" in
    iterm | \
        tmux-truecolor | \
        linux-truecolor | \
        xterm-truecolor | \
        screen-truecolor) return 0 ;;
    esac

    return 1
}

# This function uses the logic from supports-hyperlinks[1][2], which is
# made by Kat Marchán (@zkat) and licensed under the Apache License 2.0.
# [1] https://github.com/zkat/supports-hyperlinks
# [2] https://crates.io/crates/supports-hyperlinks
#
# Copyright (c) 2021 Kat Marchán
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
supports_hyperlinks() {
    # $FORCE_HYPERLINK must be set and be non-zero (this acts as a logic bypass)
    if [ -n "$FORCE_HYPERLINK" ]; then
        [ "$FORCE_HYPERLINK" != 0 ]
        return $?
    fi

    # If stdout is not a tty, it doesn't support hyperlinks
    is_tty || return 1

    # DomTerm terminal emulator (domterm.org)
    if [ -n "$DOMTERM" ]; then
        return 0
    fi

    # VTE-based terminals above v0.50 (Gnome Terminal, Guake, ROXTerm, etc)
    if [ -n "$VTE_VERSION" ]; then
        [ $VTE_VERSION -ge 5000 ]
        return $?
    fi

    # If $TERM_PROGRAM is set, these terminals support hyperlinks
    case "$TERM_PROGRAM" in
    Hyper | iTerm.app | terminology | WezTerm) return 0 ;;
    esac

    # kitty supports hyperlinks
    if [ "$TERM" = xterm-kitty ]; then
        return 0
    fi

    # Windows Terminal also supports hyperlinks
    if [ -n "$WT_SESSION" ]; then
        return 0
    fi

    # Konsole supports hyperlinks, but it's an opt-in setting that can't be detected
    # https://github.com/ohmyzsh/ohmyzsh/issues/10964
    # if [ -n "$KONSOLE_VERSION" ]; then
    #   return 0
    # fi

    return 1
}

# Adapted from code and information by Anton Kochkov (@XVilka)
# Source: https://gist.github.com/XVilka/8346728
supports_truecolor() {
    case "$COLORTERM" in
    truecolor | 24bit) return 0 ;;
    esac

    case "$TERM" in
    iterm | \
        tmux-truecolor | \
        linux-truecolor | \
        xterm-truecolor | \
        screen-truecolor) return 0 ;;
    esac

    return 1
}

setup_color() {
    # Only use colors if connected to a terminal
    if ! is_tty; then
        FMT_RAINBOW=""
        FMT_RED=""
        FMT_GREEN=""
        FMT_YELLOW=""
        FMT_BLUE=""
        FMT_BOLD=""
        FMT_RESET=""
        return
    fi

    if supports_truecolor; then
        FMT_RAINBOW="
      $(printf '\033[38;2;255;0;0m')
      $(printf '\033[38;2;255;97;0m')
      $(printf '\033[38;2;247;255;0m')
      $(printf '\033[38;2;0;255;30m')
      $(printf '\033[38;2;77;0;255m')
      $(printf '\033[38;2;168;0;255m')
      $(printf '\033[38;2;245;0;172m')
    "
        FMT_PURPLE=$(printf '\033[38;2;245;0;172m')
    else
        FMT_RAINBOW="
      $(printf '\033[38;5;196m')
      $(printf '\033[38;5;202m')
      $(printf '\033[38;5;226m')
      $(printf '\033[38;5;082m')
      $(printf '\033[38;5;021m')
      $(printf '\033[38;5;093m')
      $(printf '\033[38;5;163m')
    "
        FMT_PURPLE=$(printf '\033[38;5;163m')
    fi

    FMT_RED=$(printf '\033[31m')
    FMT_GREEN=$(printf '\033[32m')
    FMT_YELLOW=$(printf '\033[33m')
    FMT_BLUE=$(printf '\033[34m')
    FMT_BOLD=$(printf '\033[1m')
    FMT_RESET=$(printf '\033[0m')
}

command_exists() {
    command -v "$@" >/dev/null 2>&1
}

user_can_sudo() {
    # Check if sudo is installed
    command_exists sudo || return 1
    # Termux can't run sudo, so we can detect it and exit the function early.
    case "$PREFIX" in
    *com.termux*) return 1 ;;
    esac
    # The following command has 3 parts:
    #
    # 1. Run `sudo` with `-v`. Does the following:
    #    • with privilege: asks for a password immediately.
    #    • without privilege: exits with error code 1 and prints the message:
    #      Sorry, user <username> may not run sudo on <hostname>
    #
    # 2. Pass `-n` to `sudo` to tell it to not ask for a password. If the
    #    password is not required, the command will finish with exit code 0.
    #    If one is required, sudo will exit with error code 1 and print the
    #    message:
    #    sudo: a password is required
    #
    # 3. Check for the words "may not run sudo" in the output to really tell
    #    whether the user has privileges or not. For that we have to make sure
    #    to run `sudo` in the default locale (with `LANG=`) so that the message
    #    stays consistent regardless of the user's locale.
    #
    ! LANG= sudo -n -v 2>&1 | grep -q "may not run sudo"
}

run_as_root() {
    if command -v sudo >/dev/null 2>&1; then
        sudo sh -c "${*}"
    else
        su -c "${*}"
    fi
}

prompt() {
    while true; do
        printf '%s%s%s' "${FMT_YELLOW}" "$1" "${FMT_RESET}" >&2
        read -rp " ${FMT_BOLD}[y/n]${FMT_RESET} " yn
        case "${yn}" in
            [Yy]*) return 0 ;;
            [Nn]*) return 1 ;;
            *)
                error "Please answer y or n"
                printf '\n' >&2
                ;;
        esac
    done
}

underline() {
    is_tty && printf '\033[4m%s\033[24m' "$*" || printf '%s' "$*"
}

link() {
    # $1: text, $2: url, $3: fallback mode
    local text="${1}"
    local url="${2:-${text}}"
    local fallback="${3:-${url}}"

    if supports_hyperlinks; then
        printf '\033]8;;%s\033\\%s\033]8;;\033\\' "$url" "$text"
        return
    fi

    case "${fallback}" in
    --text) printf '%s\n' "$text" ;;
    --url | *) underline "$url" ;;
    esac
}

# shellcheck disable=SC2016 # backtick in single-quote
fmt_code() {
    is_tty && printf '\033[2m%s\033[22m' "$*" || printf '`%s`' "$*"
}

codeblock() {
    fmt_code "$*"
    printf '\n'
}

success() {
    printf '%s%s%s\n' "${FMT_BOLD}${FMT_GREEN}" "$*" "$FMT_RESET" >&2
}

info() {
    printf '%s%s%s\n' "${FMT_BOLD}${FMT_BLUE}" "$*" "$FMT_RESET" >&2
}

warning() {
    printf '%s%s%s\n' "${FMT_BOLD}${FMT_YELLOW}" "$*" "$FMT_RESET" >&2
}

error() {
    printf '%s%s%s\n' "${FMT_BOLD}${FMT_RED}" "$*" "$FMT_RESET" >&2
}

# Header logging
header() {
    text=${@}
    total_chars=${#text}

    if [ "$total_chars" -gt 80 ]; then
        total_chars=80
    fi

    printf "$(tput setaf 7)%s$(tput sgr0)\n" "$text" >&2
    for ((i = 1; i <= $total_chars; i++)); do
        printf "$(tput setaf 237)-$(tput sgr0)" >&2
    done
    printf '\n'  >&2
}

# # Success logging
# function success() {
#     printf "$(tput setaf 64)✓ %s$(tput sgr0)\n" "$@"
# }

# # Info logging
# function info() {
#     printf "$(tput setaf 27)INFO: %s$(tput sgr0)\n" "$@"
# }

# # Warning logging
# function warning() {
#     printf "$(tput setaf 136)WARN: %s$(tput sgr0)\n" "$@"
# }

# # Error logging
# function error() {
#     printf "$(tput setaf 1)ERR: %s$(tput sgr0)\n" "$@"
# }

# function echo_green() {
#     printf "$(tput setaf 64)%s$(tput sgr0)\n" "$@"
# }

# function echo_blue() {
#     printf "$(tput setaf 27)%s$(tput sgr0)\n" "$@"
# }

# function echo_yellow() {
#     printf "$(tput setaf 136)%s$(tput sgr0)\n" "$@"
# }

# function echo_red() {
#     printf "$(tput setaf 1)%s$(tput sgr0)\n" "$@"
# }

# function separator() {
#     for ((i = 1; i <= 80; i++)); do
#         printf "$(tput setaf 237)-$(tput sgr0)"
#     done
#     echo
# }

abspath(){
    readlink --canonicalize-missing "$1"
}

is_in() {
    local check="${1}"
    shift
    local items=("${@}")

    for item in "${items[@]}"; do
        if [[ "${check}" == "${item}" ]]; then
            return 0
        fi
    done

    return 1
}

# Test whether we're in a git repo
is_git_repo() {
    $(git rev-parse --is-inside-work-tree &> /dev/null)
}

rcurl() {
    URL="${1:-}"

    # Attempt to make all curl commands more resilient to failure. The speed
    # flags help protect against zombie connections while still allowing long
    # downloads on slower connections (avoiding --max-time).
    #
    # At the same time, let stderr get printed in real-time. If errors occur,
    # producee a final error message so folks know we cannot continue.
    args=(
        "--silent"
        "--show-error"
        "--fail"
        "--connect-timeout" "10"
        "--retry" "4"
        "--retry-all-errors"
        "--speed-limit" "100"
        "--speed-time" "30"
        "--location"
    )

    args+=("${@}")

    if ! curl "${args[@]}"; then
        error "'${URL}' didn't respond successfully, retry or check your connection, aborting!"
        return 1
    fi
}

# Detect the OS/distribution
detect_os() {
    # Default to unknown
    OS_TYPE="unknown"
    OS_KERNEL="$(uname -r)"
    OS_VERSION="$(uname -r)"
    CPU_ARCH="$(uname -m)"

    # Check for macOS first
    if [[ "$OSTYPE" == "darwin"* ]]; then
        OS_TYPE="darwin"
        OS_DISTRO="macos"
        OS_DISTRO_ORIGINAL="${OS_DISTRO}"
        OS_DISTRO_LIKE="${OS_DISTRO}"
    fi

    # Check for Termux (Android)
    if [[ -n "$PREFIX" ]] && [[ "$PREFIX" == *com.termux* ]]; then
        OS_TYPE="termux"
    elif [[ "$OSTYPE" == "linux"* ]]; then
        OS_TYPE="linux"
    fi

    if [[ "$OS_TYPE" == "unknown" ]]; then
        # Determine OS type
        if command -v uname >/dev/null 2>&1; then
            local uname_output=$(uname -s | tr '[:upper:]' '[:lower:]')
            case "$uname_output" in
                linux)
                    OS_TYPE="linux"
                    ;;
                *)
                    OS_TYPE="unix"
                    ;;
            esac
        fi
    fi

    # Check for various Linux distributions
    if command -v lsb_release >/dev/null 2>&1; then
        OS_DISTRO=$(lsb_release -si | tr '[:upper:]' '[:lower:]')
    fi

    # Alternative detection methods for distributions without lsb_release
    if [[ -f /etc/os-release ]]; then
        read -r OS_DISTRO OS_DISTRO_LIKE OS_VERSION <<<"$(. /etc/os-release && echo "${ID}" "${ID_LIKE:-"${ID}"}" "${BUILD_ID:-"${VERSION_ID:-"${VERSION_CODENAME:-}"}"}")"
        OS_DISTRO="$(echo "$OS_DISTRO" | tr '[:upper:]' '[:lower:]')"

        # Technically ID_LIKE can have a space separated list of distros as
        # it's more reliable for derivatives, but currently we really only
        # care that we have a Arch based system.
        case "$OS_DISTRO" in
            *debian*|*ubuntu*|*mint*|pop|elementary|zorin)
                OS_DISTRO_LIKE="debian"
                ;;
            *redhat*|*fedora*|*centos*|*rhel*|*ol*|*almalinux*|*rocky*|*scientific*)
                OS_DISTRO_LIKE="redhat"
                ;;
            *arch*|*manjaro*|*endeavouros*|*garuda*|*arcolinux*|*reborn*|cachyos)
                OS_DISTRO_LIKE="arch"
                ;;
            *suse*|*sles*|*caasp*)
                OS_DISTRO_LIKE="suse"
                ;;
            *alpine*)
                OS_DISTRO_LIKE="alpine"
                ;;
            *)
                # Check ID if ID_LIKE didn't match
                warning "Got un-catched OS_DISTRO \"$OS_DISTRO\" ($OS_DISTRO_LIKE)"
                ;;
        esac
    fi

    # Check specific files that identify distributions
    if [[ -f /etc/debian_version ]]; then
        OS_DISTRO_LIKE="debian"
    elif [[ -f /etc/redhat-release ]]; then
        OS_DISTRO_LIKE="redhat"
    elif [[ -f /etc/arch-release ]]; then
        OS_DISTRO_LIKE="arch"
    elif [[ -f /etc/SuSE-release ]]; then
        OS_DISTRO_LIKE="suse"
    elif [[ -f /etc/alpine-release ]]; then
        OS_DISTRO_LIKE="alpine"
    fi

    # Are we in WSL?
    if grep --quiet --ignore-case "microsoft" /proc/version; then
        OS_IN_WSL="yes"
    fi

    # We can't fully depend on these which is why this env var exists, but it
    # at least protects someone running this script who didn't pass in the
    # environment variable in the common case (Docker or Podman).
    [[ -f "/.dockerenv" || -f "/run/.containerenv" ]] && OS_IN_CONTAINER="yes"

    # Can we install and configure a window manager and GUI tools?
    if [[ "${OS_TYPE}" == "linux" && "${OS_DISTRO_LIKE}" = "arch" && "${OS_IN_WSL}" != "yes" && "${OS_IN_CONTAINER}" != "yes" ]]; then
        DOTY_GUI_ELIGIBLE="yes"
    fi

    if [[ "${DOTY_GUI_ENABLED}" == "yes" && "${DOTY_GUI_ELIGIBLE}" == "yes" ]]; then
        DOTY_GUI_ENABLED="yes"
    else
        DOTY_GUI_ENABLED="no"
    fi
}

setup_color
