#!/usr/bin/env bash

# Easier navigation: .., ..., ...., ....., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ~="cd ~" # `cd` is probably faster to type though
alias -- -="cd -"

# Shortcuts
alias dl="cd ~/Downloads"
alias dt="cd ~/Desktop"
alias g="git"
alias cl="clear"
alias clr='clear; clear; printf "Currently logged in on \033[32m%s\033[0m is \033[1m\033[38;2;245;0;172m%s\033[0m in directory \033[33m%s\033[0m.\n" "$TTY" "$USERNAME" "$PWD" >&2'

alias p='ping -c 5'
alias p6='ping6 -c 5'
alias path='print -l $path'
alias mkd='mkdir -pv'
# get top process eating memory
alias psmem='ps -e -orss=,args= | sort -b -k1 -nr'
alias psmem10='ps -e -orss=,args= | sort -b -k1 -nr | head -n 10'
# get top process eating cpu if not work try execute : export LC_ALL='C'
alias pscpu='ps -e -o pcpu,cpu,nice,state,cputime,args | sort -k1,1n -nr'
alias pscpu10='ps -e -o pcpu,cpu,nice,state,cputime,args | sort -k1,1n -nr | head -n 10'
# top10 of the history
alias hist10='print -l ${(o)history%% *} | uniq -c | sort -nr | head -n 10'

export CLICOLOR=1

# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then # GNU `ls`
	colorflag="--color"
	# export LS_COLORS='no=00:fi=00:di=01;31:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:'
	export LS_COLORS='di=1;31:ln=36:so=1;37:pi=1;33:ex=35:bd=37:cd=37:su=37:sg=37:tw=32:ow=1;32'
else # macOS `ls`
	colorflag="-G"
	# export LSCOLORS='Gxfxcxdxbxegedabagacad'
	# export LSCOLORS='gxBxhxDxfxhxhxhxhxcxcx'
	export LSCOLORS='BxgxHxDxfxhxhxhxhxcxCx'
fi

# List dir contents aliases
# ls, the common ones I use a lot shortened for rapid fire usage
# ref: http://ss64.com/osx/ls.html
# List all files colorized in long format
alias l="ls -lFh ${colorflag}"     # size,show type,human readable
# List all except . and ..., color, mark file types, long form no user group, file size
alias la="ls -AFoh ${colorflag}"
# List only directories
alias ld="ls -lF ${colorflag}"
# List all except . and ..., color, mark file types, long form no use group, order by last modified, file size
alias lat="ls -AFoth ${colorflag}"
# Always use color output for `ls`
alias ls="command ls ${colorflag}"
# Order by last modified, long form no user group, color
alias lt="ls -to ${colorflag}"
alias ldot="ls -ld .* ${colorflag}"
 #A column contains name of files and directories
alias lrt="ls -1Fcrt ${colorflag}"
alias lart="ls -1Fcart ${colorflag}"
# List file size
alias li="ls -1FSsh ${colorflag}"

# alias lsr="ls -lARFh ${colorflag}" # Recursive list of files and directories
# alias lr="ls -tRFh ${colorflag}"   # sorted by date,recursive,show type,human readable
# alias lt="ls -ltFh ${colorflag}"   # long list,sorted by date,show type,human readable

alias tl="tree -L 2 -a -s -p"

unset colorflag;

alias e='echo'
# Replace cat with bat to support syntax highligthing.
alias c='bat'
# Concatenate and print content of files (add line numbers)
alias cn="cat -n"

# Always enable colored `grep` output
# Note: `GREP_OPTIONS="--color=auto"` is deprecated, hence the alias usage.
# alias grep='GREP_COLOR="1;33;40" LANG=C grep --color=auto'
alias grep='grep --color=auto'
alias sgrep='grep -R -n -H -C 5 --exclude-dir={.git,.svn,CVS} '
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

alias t='tail -f'

# Command line head / tail shortcuts
alias -g H='| head'
alias -g T='| tail'
alias -g G='| grep'
alias -g L="| less"
alias -g M="| most"
alias -g LL="2>&1 | less"
alias -g CA="2>&1 | cat -A"
alias -g NE="2> /dev/null"
alias -g NUL="> /dev/null 2>&1"
alias -g P="2>&1| pygmentize -l pytb"

alias dud='du -d 1 -h'
(( $+commands[duf] )) || alias duf='du -sh *'
(( $+commands[fd] )) || alias fd='find . -type d -name'
alias ff='find . -type f -name'

# Open file in existing MacVim window
alias v="nvim"
alias gvim="open -a MacVim"
alias mvim="open -a MacVim"

# Enable aliases to be sudo'ed
alias s='sudo '

# Get week number
alias week='date +%V'
# Get now timestamp
alias now="date +%s"

# IP addresses
alias getip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# Show active network interfaces
alias ifactive="ifconfig | pcregrep -M -o '^[^\t:]+:([^\n]|\n\t)*status: active'"

# Canonical hex dump; some systems have this symlinked
command -v hd > /dev/null || alias hd="hexdump -C"
# macOS has no `md5sum`, so use `md5` as a fallback
command -v md5sum > /dev/null || alias md5sum="md5"
# macOS has no `sha1sum`, so use `shasum` as a fallback
command -v sha1sum > /dev/null || alias sha1sum="shasum"

# Trim new lines and copy to clipboard
alias tc="tr -d '\n' | pbcopy"

# Intuitive map function
# For example, to list all directories that contain a certain file:
# find . -name .gitattributes | map dirname
alias map="xargs -n1"

# One of @janmoesen's ProTip's
for method in GET HEAD POST PUT DELETE TRACE OPTIONS; do
	alias "${method}"="lwp-request -Use -H 'User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)' -m '${method}'"
done

# Reload the shell (i.e. invoke as a login shell)
alias reload="exec ${SHELL} -l"

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

if [[ "${OSTYPE}" == darwin* ]]; then
	__maliases_file="${HOME}/.doty/shell/macos/aliases";
	[ -r "$__maliases_file" ] && [ -f "$__maliases_file" ] && source "$__maliases_file";
	unset __maliases_file;
fi

alias decodejwt="jq -R 'split(\".\") | {\"headers\": .[0] | @base64d | fromjson, \"body\": .[1] | @base64d | fromjson}'"
